[32mINFO    [0m BasePage:base_page.py:66 Navigating to: http://localhost:5173/blogs
[32mINFO    [0m TestSpecificBlogDetail:test_specific_blog_detail.py:331 Found 5 clickable blog elements: ('css selector', 'article')
[32mINFO    [0m TestSpecificBlogDetail:test_specific_blog_detail.py:341 âœ… Successfully navigated to: http://localhost:5173/blogs/684c6f3c2ad340bafd4e5370
[32mINFO    [0m TestSpecificBlogDetail:test_specific_blog_detail.py:179 Found blog detail indicator: ('css selector', 'article')
[32mINFO    [0m TestSpecificBlogDetail:test_specific_blog_detail.py:346 âœ… Blog detail page loaded from navigation
[32mINFO    [0m utils.driver_manager:driver_manager.py:190 WebDriver quit successfully
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFAACAD580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/79d64daadf7e3cde1bf1ddfebcc1579f/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFAACAD940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/79d64daadf7e3cde1bf1ddfebcc1579f/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFAACADB50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/79d64daadf7e3cde1bf1ddfebcc1579f/element
[31m[1mERROR   [0m LoginPage:login_page.py:414 Exception during logout: HTTPConnectionPool(host='localhost', port=52975): Max retries exceeded with url: /session/79d64daadf7e3cde1bf1ddfebcc1579f/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FFAACADD60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[32mINFO    [0m TestSpecificBlogDetail:test_specific_blog_detail.py:36 âœ… Test completed: test_blog_list_navigation_if_available